#!/bin/sh

# populate /web if empty

if [ ! -d /web/config ]; then
	mkdir -p /web/config
	chown -R apache.www-data /web
fi

if [ ! -d /web/logs ]; then
	mkdir /web/logs
	chown -R apache.www-data /web/logs
fi

if [ ! -f /web/config/httpd.conf ]; then
	cp -R /etc/apache2/* /web/config/
	chown -R apache.www-data /web/config
	# fix bug in httpd.conf
	sed -i 's/^Group apache/Group www-data/' /web/config/httpd.conf
fi

if [ ! -d /web/modules ]; then
	ln -s /usr/lib/apache2 /web/modules
fi

if [ ! -d /web/run ]; then
	mkdir -p /web/run
	chown -R apache.www-data /web/config
fi

rm -f /web/run/httpd.pid