#!/bin/sh

# copy index.html if html directory does not exists

#if [ ! -d /web/html ]; then
  # mkdir /web/html
  # cp -RpP /etc/apache2/html/* /web/html/
  # chown -R apache.www-data /web/html
if [ ! -d /web/PluXml ]; then
  echo "Téléchargement de PluXml"
  tmpfile="/tmp/pluxml.zip"
  wget -O ${tmpfile} ${PLUXML_URL}
  unzip -qd /web/ ${tmpfile}
  rm ${tmpfile}
  PHP_INFO="/etc/apache2/html/phpinfo.php"
  chown -R apache.www-data ${PHP_INFO}
  ln -s ${PHP_INFO} ${DOCUMENT_ROOT}/phpinfo.php

  echo "Téléchargement du plugin kzUploader"
  wget -O ${tmpfile} "http://kazimentou.fr/pluxml-plugins2/index.php?plugin=kzUploader&download"
  unzip -qd ${DOCUMENT_ROOT}/plugins/ ${tmpfile}
  rm ${tmpfile}
fi

SEP="====================================================="
echo ${SEP}
echo " Connectez votre navigateur à l'adresse: $(tail -n 1 /etc/hosts | sed 's/\s.*$//')"
echo " Date/heure: $(date)"
echo ${SEP}