#!/bin/sh

if [ ! -d /web/PluXml ]; then
	echo -e "\nTéléchargement de la dernière version de PluXml"
	tmpfile="/tmp/pluxml.zip"
	wget -qO ${tmpfile} ${PLUXML_URL}
	unzip -qd /web/ ${tmpfile}
	rm ${tmpfile}

	echo '<?php phpinfo(); ?>' > ${DOCUMENT_ROOT}/phpinfo.php

	echo "Téléchargement de(s) plugin(s) :"
	# plugins="kzUploader moveMyDatas DnD_move tinyMCE"
	plugins="kzUploader"
	for plugin in ${plugins}; do
		echo -e "\e[33m${plugin}\e[0m"
		wget -qO ${tmpfile} "http://kazimentou.fr/pluxml-plugins2/index.php?plugin=${plugin}&download"
		unzip -qd ${DOCUMENT_ROOT}/plugins/ ${tmpfile}
	done
	rm ${tmpfile}

	chown -R apache.www-data ${DOCUMENT_ROOT}
fi

SEP="====================================================="
IP_ADDR=$(tail -n 1 /etc/hosts | sed 's/\s.*$//')
echo -e "${SEP}"
echo -e "\e[33mConnectez votre navigateur à une des adresses suivantes :"
echo -e "  - http://${IP_ADDR}"
echo -e "  - http://${IP_ADDR}/phpinfo.php\e[0m\n"
echo -e "Date/heure: $(date)\n"
$(ls /usr/bin/php* | head -1) --version
echo -e "\nMontez le volume de données sur le dossier \e[33m/web\e[0m"
echo ${SEP}